{
  "hash": "07682a9674ad3b4f5483a11afbc0a209",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Biomarker-Stratified Treatment Effect in Real-World Colon Cancer Data\"\nsubtitle: \"From cohort to subgroup forest plot — a reproducible RWE Analysis Report\"\nauthor: \"Natália S Kugel, PhD\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: show\n    theme: default\n    embed-resources: true\nbibliography: references.bib\n---\n\n\n\n\n\n# Background and objective\n\nPrecision medicine asks a deceptively simple question: **does this\ntreatment work better in some patients than in others?**  In a regulated\nRWE submission, answering this question requires a transparent and\nreproducible chain of evidence: a clearly specified cohort, a\npre-defined biomarker, pre-specified subgroups, and statistical methods\nthat handle the time-to-event nature of the data correctly.\n\nIn this report we use the publicly available **NCCTG colon adjuvant\nchemotherapy cohort** (`survival::colon`) [@moertel1990levamisole] as a\nstand-in for an EHR-derived oncology dataset. The trial compared\nobservation versus levamisole + 5-FU in resected colon cancer. We\naugment the cohort with a *simulated* tumor biomarker (think MSI status\nor a gene-expression signature) and ask:\n\n> **Does the treatment effect on overall survival differ between\n> biomarker-positive and biomarker-negative patients?**\n\n::: {.callout-note}\n## Content\n\nBy the end of this report you should be able to:\n\n1.  Load and clean a real-world cohort.\n2.  Stratify a cohort by a biomarker.\n3.  Estimate Kaplan–Meier survival curves and Cox HRs by subgroup.\n4.  Test a treatment-by-biomarker interaction.\n5.  Visualize subgroup HRs in a forest plot.\n6.  Interpret the results in a regulatory context.\n7.  Discuss the limitations and what a regulator would want to see next.\n:::\n\n# Cohort\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohort <- load_colon() |> add_biomarker(prevalence = 0.35, seed = 7)\nglimpse(cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 619\nColumns: 14\n$ id        <dbl> 1, 2, 3, 4, 5, 6, 8, 10, 12, 13, 15, 16, 19, 21, 24, 25, 26,…\n$ age       <dbl> 43, 63, 71, 66, 69, 57, 54, 68, 52, 64, 46, 68, 34, 64, 50, …\n$ sex       <fct> Male, Male, Female, Female, Male, Female, Male, Female, Male…\n$ obstruct  <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, …\n$ perfor    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ adhere    <dbl> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …\n$ nodes     <dbl> 5, 1, 7, 6, 22, 9, 1, 1, 2, 1, 4, 1, 1, 1, 1, 4, 1, 13, 6, 1…\n$ differ    <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, …\n$ extent    <dbl> 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 1, …\n$ surg      <dbl> 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, …\n$ treatment <fct> Lev+5FU, Lev+5FU, Obs, Lev+5FU, Obs, Lev+5FU, Obs, Lev+5FU, …\n$ time      <dbl> 1521, 3087, 963, 293, 659, 1767, 3192, 3308, 3309, 2085, 275…\n$ status    <dbl> 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, …\n$ biomarker <fct> Positive, Negative, Negative, Negative, Negative, Negative, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncohort |>\n  select(treatment, biomarker, age, sex, nodes, differ, extent) |>\n  tbl_summary(\n    by = treatment,\n    statistic = list(all_continuous() ~ \"{mean} ({sd})\",\n                     all_categorical() ~ \"{n} ({p}%)\"),\n    missing = \"ifany\"\n  ) |>\n  add_overall() |>\n  modify_caption(\"**Table 1. Baseline characteristics by treatment arm.**\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gvjvgqlita\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gvjvgqlita table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gvjvgqlita thead, #gvjvgqlita tbody, #gvjvgqlita tfoot, #gvjvgqlita tr, #gvjvgqlita td, #gvjvgqlita th {\n  border-style: none;\n}\n\n#gvjvgqlita p {\n  margin: 0;\n  padding: 0;\n}\n\n#gvjvgqlita .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gvjvgqlita .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gvjvgqlita .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gvjvgqlita .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gvjvgqlita .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gvjvgqlita .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gvjvgqlita .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gvjvgqlita .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gvjvgqlita .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gvjvgqlita .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gvjvgqlita .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gvjvgqlita .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gvjvgqlita .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gvjvgqlita .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gvjvgqlita .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvjvgqlita .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gvjvgqlita .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gvjvgqlita .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gvjvgqlita .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvjvgqlita .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gvjvgqlita .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvjvgqlita .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gvjvgqlita .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvjvgqlita .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gvjvgqlita .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvjvgqlita .gt_left {\n  text-align: left;\n}\n\n#gvjvgqlita .gt_center {\n  text-align: center;\n}\n\n#gvjvgqlita .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gvjvgqlita .gt_font_normal {\n  font-weight: normal;\n}\n\n#gvjvgqlita .gt_font_bold {\n  font-weight: bold;\n}\n\n#gvjvgqlita .gt_font_italic {\n  font-style: italic;\n}\n\n#gvjvgqlita .gt_super {\n  font-size: 65%;\n}\n\n#gvjvgqlita .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gvjvgqlita .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gvjvgqlita .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gvjvgqlita .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gvjvgqlita .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gvjvgqlita .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gvjvgqlita .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gvjvgqlita .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gvjvgqlita div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <caption><span data-qmd-base64=\"KipUYWJsZSAxLiBCYXNlbGluZSBjaGFyYWN0ZXJpc3RpY3MgYnkgdHJlYXRtZW50IGFybS4qKg==\"><span class='gt_from_md'><strong>Table 1. Baseline characteristics by treatment arm.</strong></span></span></caption>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNjE5\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 619</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipPYnMqKiAgCk4gPSAzMTU=\"><span class='gt_from_md'><strong>Obs</strong><br />\nN = 315</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipMZXYrNUZVKiogIApOID0gMzA0\"><span class='gt_from_md'><strong>Lev+5FU</strong><br />\nN = 304</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">biomarker</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Negative</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">402 (65%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">202 (64%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">200 (66%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Positive</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">217 (35%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">113 (36%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">104 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">60 (12)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">59 (12)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">60 (12)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">312 (50%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">149 (47%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">163 (54%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">307 (50%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">166 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">141 (46%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">nodes</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3.6 (3.6)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3.8 (3.7)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3.5 (3.4)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">12</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">differ</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">56 (9.2%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">27 (8.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">29 (9.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">444 (73%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">229 (74%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">215 (72%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">106 (17%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">52 (17%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">54 (18%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">13</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">7</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">6</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">extent</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">18 (2.9%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8 (2.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">10 (3.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">70 (11%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">38 (12%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">32 (11%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">500 (81%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">249 (79%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">251 (83%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">31 (5.0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">20 (6.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (3.6%)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk7IE1lYW4gKFNEKQ==\"><span class='gt_from_md'>n (%); Mean (SD)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n# Overall Kaplan–Meier\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- survfit(Surv(time, status) ~ treatment, data = cohort)\nggsurvplot(fit, data = cohort, conf.int = TRUE, risk.table = TRUE,\n           palette = c(\"#4C78A8\", \"#F58518\"),\n           legend.labs = c(\"Obs\", \"Lev+5FU\"),\n           xlab = \"Days since enrollment\", ylab = \"Overall survival\")\n```\n\n::: {.cell-output-display}\n![**Overall survival by treatment arm.** Kaplan–Meier estimates of overall survival in the full cohort (n = 619; 291 deaths) comparing adjuvant Lev+5FU (orange) versus observation (blue). Shaded bands denote pointwise 95% confidence intervals; the risk table below the curves reports the number of patients still at risk at each timepoint. The Lev+5FU curve lies consistently above the observation curve from approximately one year onward, indicating a sustained survival advantage. This visual separation is consistent with the unadjusted hazard ratio of 0.69 (95% CI 0.55–0.87; p = 0.002) reported in Section *Subgroup hazard ratios*. Time is expressed in days since enrollment.](report_files/figure-html/fig-km-overall-1.png){#fig-km-overall width=768}\n:::\n:::\n\n\n\n# Biomarker-stratified Kaplan–Meier\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_pos <- survfit(Surv(time, status) ~ treatment,\n                   data = filter(cohort, biomarker == \"Positive\"))\nfit_neg <- survfit(Surv(time, status) ~ treatment,\n                   data = filter(cohort, biomarker == \"Negative\"))\n\np_pos <- ggsurvplot(fit_pos, data = filter(cohort, biomarker == \"Positive\"),\n                    conf.int = TRUE, palette = c(\"#4C78A8\", \"#F58518\"),\n                    title = \"Biomarker positive\",\n                    legend.labs = c(\"Obs\", \"Lev+5FU\"))$plot\np_neg <- ggsurvplot(fit_neg, data = filter(cohort, biomarker == \"Negative\"),\n                    conf.int = TRUE, palette = c(\"#4C78A8\", \"#F58518\"),\n                    title = \"Biomarker negative\",\n                    legend.labs = c(\"Obs\", \"Lev+5FU\"))$plot\ngridExtra::grid.arrange(p_pos, p_neg, ncol = 2)\n```\n\n::: {.cell-output-display}\n![**Overall survival by treatment arm, stratified by biomarker status.** Kaplan–Meier curves for Lev+5FU (orange) versus observation (blue) in biomarker-positive (left; n = 217, 102 events) and biomarker-negative (right; n = 402, 189 events) strata. Shaded bands denote 95% pointwise confidence intervals. Curve separation is visually similar across strata, consistent with subgroup HRs of 0.70 (95% CI 0.48–1.04) and 0.68 (95% CI 0.51–0.91) and a non-significant pre-specified treatment-by-biomarker interaction test (LRT p = 0.89). The wider confidence bands in the biomarker-positive panel reflect the smaller number of events rather than a diminished treatment effect.](report_files/figure-html/fig-km-strat-1.png){#fig-km-strat width=960}\n:::\n:::\n\n\n\n# Subgroup hazard ratios\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg <- fit_subgroup_hr(cohort) |>\n  filter(term == \"treatmentLev+5FU\") |>\n  transmute(subgroup, n, events,\n            HR = round(estimate, 2),\n            `95% CI` = sprintf(\"%.2f – %.2f\", conf.low, conf.high),\n            `p-value` = signif(p.value, 3))\nknitr::kable(sg,\n             caption = \"Treatment effect (Lev+5FU vs Obs) on OS by biomarker stratum.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Treatment effect (Lev+5FU vs Obs) on OS by biomarker stratum.\n\n|subgroup           |   n| events|   HR|95% CI      | p-value|\n|:------------------|---:|------:|----:|:-----------|-------:|\n|Overall            | 619|    291| 0.69|0.55 – 0.87 | 0.00170|\n|Biomarker positive | 217|    102| 0.70|0.47 – 1.04 | 0.08150|\n|Biomarker negative | 402|    189| 0.68|0.51 – 0.91 | 0.00859|\n\n\n:::\n:::\n\n\n\n\n**Interpretation:** \nAdjuvant Lev+5FU was associated with a statistically\nsignificant reduction in the hazard of death in the overall cohort\n(HR 0.69, 95% CI 0.55–0.87; p = 0.0017), corresponding to an estimated\n31% relative risk reduction versus observation. Subgroup-specific\nestimates were essentially identical in biomarker-positive\n(HR 0.70, 95% CI 0.48–1.04) and biomarker-negative\n(HR 0.68, 95% CI 0.51–0.91) patients, with fully overlapping confidence\nintervals. The wider interval and larger p-value in the\nbiomarker-positive subgroup reflect the smaller number of events\n(n = 102 vs. 189) rather than a smaller treatment effect; the difference\nin subgroup p-values is therefore **not** evidence of effect\nmodification. Formal assessment of a predictive biomarker effect is\ndeferred to the pre-specified treatment-by-biomarker interaction test\n(Section *Treatment × biomarker interaction*), in line with regulatory\nguidance that subgroup p-value comparisons should not be used to infer\nheterogeneity of treatment effect.\n\n\n## Forest plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_data <- fit_subgroup_hr(cohort) |>\n  filter(term == \"treatmentLev+5FU\") |>\n  mutate(label = sprintf(\"%s (n=%d, events=%d)\", subgroup, n, events))\n\nggplot(plot_data,\n       aes(y = reorder(label, estimate),\n           x = estimate, xmin = conf.low, xmax = conf.high)) +\n  geom_pointrange(color = \"#1f77b4\", size = 0.6) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  scale_x_log10() +\n  labs(x = \"Hazard ratio (log scale)\", y = NULL,\n       title = \"Forest plot: treatment effect by biomarker subgroup\",\n       subtitle = \"HR < 1 favors Lev+5FU\")\n```\n\n::: {.cell-output-display}\n![**Forest plot of treatment effect on overall survival by biomarker subgroup.** Hazard ratios (HR) for Lev+5FU vs. observation are shown on a logarithmic scale; horizontal lines denote 95% confidence intervals. Point estimates were near-identical across biomarker-positive (HR 0.70) and biomarker-negative (HR 0.68) strata, with overlapping confidence intervals, consistent with the non-significant pre-specified interaction test (LRT p = 0.89). The wider interval in the biomarker-positive subgroup reflects fewer events (102 vs. 189) rather than a smaller treatment effect.](report_files/figure-html/fig-forest-1.png){#fig-forest width=960}\n:::\n:::\n\n\n\n# Treatment × biomarker interaction\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout <- fit_interaction_cox(cohort)\nout$coefs |>\n  transmute(term, HR = round(estimate, 2),\n            `95% CI` = sprintf(\"%.2f – %.2f\", conf.low, conf.high),\n            `p-value` = signif(p.value, 3)) |>\n  knitr::kable(caption = \"Adjusted Cox model with treatment x biomarker interaction.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Adjusted Cox model with treatment x biomarker interaction.\n\n|term                               |   HR|95% CI      | p-value|\n|:----------------------------------|----:|:-----------|-------:|\n|treatmentLev+5FU                   | 0.67|0.50 – 0.90 | 0.00744|\n|biomarkerPositive                  | 1.01|0.73 – 1.38 | 0.96200|\n|age                                | 1.00|0.99 – 1.01 | 0.92700|\n|sexMale                            | 0.87|0.69 – 1.10 | 0.23500|\n|nodes                              | 1.11|1.09 – 1.14 | 0.00000|\n|treatmentLev+5FU:biomarkerPositive | 0.97|0.59 – 1.59 | 0.89200|\n\n\n:::\n:::\n\n\n\nThe likelihood-ratio test p-value for the interaction is\n**0.892**.\n\n\n**Interpretation.** \nThe pre-specified treatment-by-biomarker interaction was not\nsignificant (HR 0.97, 95% CI 0.59–1.59; LRT p = 0.89), providing\nno evidence of a predictive biomarker effect; the overall survival\nbenefit of Lev+5FU was consistent across biomarker strata.\n\n\n# Limitations and discussion\n\n- The biomarker here is **simulated**; in a real submission, biomarker\n  assay validation and pre-specification are essential.\n- The colon dataset is from a randomized trial — for a true RWE study,\n  one would also handle confounding (e.g., propensity score adjustment).\n- Multiplicity: subgroup HRs and the interaction test should be\n  interpreted with appropriate adjustment.\n- The proportional-hazards assumption should be checked\n  (`cox.zph`) — left as an exercise.\n\n# Reproducibility\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.4.3 (2025-02-28)\nPlatform: x86_64-pc-linux-gnu\nRunning under: Ubuntu 24.04.2 LTS\n\nMatrix products: default\nBLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 \nLAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Etc/UTC\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] broom_1.0.7       gtsummary_2.5.0   survminer_0.5.2   ggpubr_0.6.3     \n[5] survival_3.8-3    ggplot2_4.0.3     dplyr_1.2.1       rwbiomarker_0.1.0\n\nloaded via a namespace (and not attached):\n [1] gt_1.3.0           sass_0.4.9         generics_0.1.3     tidyr_1.3.1       \n [5] rstatix_0.7.3      xml2_1.3.6         stringi_1.8.4      lattice_0.22-6    \n [9] digest_0.6.37      magrittr_2.0.3     evaluate_1.0.3     grid_4.4.3        \n[13] RColorBrewer_1.1-3 cards_0.7.1        fastmap_1.2.0      jsonlite_1.9.0    \n[17] Matrix_1.7-2       backports_1.5.0    Formula_1.2-5      ggtext_0.1.2      \n[21] gridExtra_2.3      purrr_1.0.4        scales_1.4.0       abind_1.4-8       \n[25] cli_3.6.6          rlang_1.2.0        litedown_0.9       commonmark_2.0.0  \n[29] splines_4.4.3      base64enc_0.1-3    withr_3.0.2        yaml_2.3.10       \n[33] tools_4.4.3        ggsignif_0.6.4     vctrs_0.7.3        R6_2.6.1          \n[37] lifecycle_1.0.5    stringr_1.5.1      fs_1.6.5           car_3.1-5         \n[41] htmlwidgets_1.6.4  pkgconfig_2.0.3    pillar_1.10.1      gtable_0.3.6      \n[45] Rcpp_1.1.1-1.1     glue_1.8.0         xfun_0.57          tibble_3.2.1      \n[49] tidyselect_1.2.1   knitr_1.51         farver_2.1.2       htmltools_0.5.8.1 \n[53] labeling_0.4.3     rmarkdown_2.31     carData_3.0-6      compiler_4.4.3    \n[57] S7_0.2.2           markdown_2.0       gridtext_0.1.6    \n```\n\n\n:::\n:::\n\n\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}